version = 0.1
[default.deploy.parameters]
stack_name = "camrie-app"
resolve_s3 = true
s3_prefix = "camrie-app"
region = "us-east-1"
profile = "nyu"
capabilities = "CAPABILITY_IAM"
image_repositories = []
